services:
  dynamixel_hardware_interface_demos:
    container_name: dynamixel_hardware_interface_demos
    image: robotis/dynamixel-hardware-interface-demos:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    tty: true
    restart: always
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    ipc: host
    pid: host
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
     # - RMW_IMPLEMENTATION=rmw_zenoh_cpp
    volumes:
      - /dev:/dev
      - /dev/shm:/dev/shm
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ../libs/DynamixelSDK:/root/ros2_ws/src/DynamixelSDK
      - ../dynamixel_hardware_interface_demos:/root/ros2_ws/src/dynamixel_hardware_interface_demos/dynamixel_hardware_interface_demos
      - ../dynamixel_hardware_interface_example:/root/ros2_ws/src/dynamixel_hardware_interface_demos/dynamixel_hardware_interface_example
      - ../dynamixel_hardware_interface_example_1:/root/ros2_ws/src/dynamixel_hardware_interface_demos/dynamixel_hardware_interface_example_1
      - ../dynamixel_hardware_interface_example_2:/root/ros2_ws/src/dynamixel_hardware_interface_demos/dynamixel_hardware_interface_example_2
      - ../dynamixel_hardware_interface_example_3:/root/ros2_ws/src/dynamixel_hardware_interface_demos/dynamixel_hardware_interface_example_3
      - ../dynamixel_hardware_interface_example_4:/root/ros2_ws/src/dynamixel_hardware_interface_demos/dynamixel_hardware_interface_example_4
      - ../dynamixel_hardware_interface_example_e2d2:/root/ros2_ws/src/dynamixel_hardware_interface_demos/dynamixel_hardware_interface_example_e2d2
    privileged: true
    command: bash
